name: Node.js CI

on:
  push:
    branches:  [master]
  pull_request:
    branches:  [master]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    steps:
      - name: Github checkout
        uses: actions/checkout@v4
        if: matrix.os == 'ubuntu-latest'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run lint:check
      - run: npm audit --audit-level=critical
      - run: npm run test:ci
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - run: npm run build
      - name: Compare Versions
        run: |
          TAG_VERSION=$(echo ${{env.TAG}} | tr -dc '0-9')
          PACKAGE_VERSION=$(echo ${{env.PACKAGE}} | tr -dc '0-9')

          if (( $((10#$PACKAGE_VERSION + 1)) > $((10#$TAG_VERSION + 1)) )); then
              echo "new version start release"
              echo "RELEASE=true" >> "$GITHUB_ENV"
          else
              echo "no new version to release"
              echo "RELEASE=false" >> "$GITHUB_ENV"
          fi
